version: "2"  # これが v2 系では必須になりました

golangci-lint:  # 全てをこの下にまとめる必要があります
  linters-settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Print

  linters:
    enable:
      - errcheck
      - gosimple
      - staticcheck
      - unused
      - govet
