// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FileMetadataStatus.
const (
	Completed  FileMetadataStatus = "completed"
	Failed     FileMetadataStatus = "failed"
	Pending    FileMetadataStatus = "pending"
	Processing FileMetadataStatus = "processing"
)

// Valid indicates whether the value is a known member of the FileMetadataStatus enum.
func (e FileMetadataStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// FileMetadata defines model for FileMetadata.
type FileMetadata struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Size      *int                `json:"size,omitempty"`
	Source    *string             `json:"source,omitempty"`
	Status    *FileMetadataStatus `json:"status,omitempty"`
	Tags      *[]string           `json:"tags,omitempty"`
}

// FileMetadataStatus defines model for FileMetadata.Status.
type FileMetadataStatus string

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	FileId *openapi_types.UUID `json:"file_id,omitempty"`
	GcsUrl *string             `json:"gcs_url,omitempty"`
	Status *string             `json:"status,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Tags 検索用タグ（複数指定可能）
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`
}

// UploadFileMultipartBody defines parameters for UploadFile.
type UploadFileMultipartBody struct {
	// File アップロードするファイル本体
	File *openapi_types.File `json:"file,omitempty"`

	// Tags 検索用タグ
	Tags *[]string `json:"tags,omitempty"`

	// TenantId ビジネスオーナー識別子（将来のDB分離用）
	TenantId *string `json:"tenant_id,omitempty"`
}

// UploadFileMultipartRequestBody defines body for UploadFile for multipart/form-data ContentType.
type UploadFileMultipartRequestBody UploadFileMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// メタデータの一覧を取得する
	// (GET /files)
	ListFiles(ctx echo.Context, params ListFilesParams) error
	// システムの稼働状況と起動時パフォーマンスを返す
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// ファイルをアップロードし、メタデータを登録する
	// (POST /upload)
	UploadFile(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListFiles converts echo context to params.
func (w *ServerInterfaceWrapper) ListFiles(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFilesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tags", ctx.QueryParams(), &params.Tags, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tags: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListFiles(ctx, params)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// UploadFile converts echo context to params.
func (w *ServerInterfaceWrapper) UploadFile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadFile(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/files", wrapper.ListFiles)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.POST(baseURL+"/upload", wrapper.UploadFile)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6RVYU8cRRj+K2T045a7tn7abzam2kSTxugnQi7D7nvHNLuz25lZUyQk7I6BK21TpEVE",
	"q1iEFq1QYlWovcqPGfY4PvEXzDt7BLjbazF+m515d+Z5n3meZyaJF4VxxIErSdxJIr1xCKkdXmUBfAKK",
	"+lRR/I5FFINQDOyqJ4Aq8GtU4Vc9EiGOiE8VXFAsBOIQNREDcYlUgvEGmXII88/UJgnzy8o4DQEL+xYk",
	"+/L0AuMKGiDsSpQIb8BPiqrEQgaehMQdITFwHxcdbMkDKYsPJCIABYipTlkAPhktQadow+7GFISy9MTu",
	"BBWCTpCpk4lo7AZ4Cis+j4OI+p+CjCMuoZ/cOgugdk62Gp6sJSJ4W++3KHaHq4mHPfdv1Q8UpxivR7iB",
	"D9ITLFYs4sQlJntu9K9Gt4x+YbJVHGSbRs/Y+dTon036LF/526TrJv3KpCv7u0/y5pLRiyZ7bLI1o591",
	"Xq0eTqfvX7+GQJiy0K5TQYMAgiGU3tBngnJZBzFUFH0BQhaHXxyuDlexvSgGTmNGXHJ5uDp8GS+UqnHb",
	"bwUptKMGWIUivRTRX/OJSz5mUl21FfiPoCEoEJK4I5OE4RE3ExAT5FiKJGAhU8TpuqOgo06TQBH3UtXp",
	"0+OUU75NVK9LGLDPgG3O0t5ee3Twx+rBww2T7Zls+6jV7KzNthe323dn863v8vvPO/r1Ues2cQjcioPI",
	"B+IqkYBTisYK+TSWcyt61CGiq11bf6latZEQcQXcsk3jOGCe5btyQyL2ybKD3hVQJy55p3ISQpVuAlXO",
	"xE8/himnl5vmfD63YmUskzCkYgJ1qh8jVXrWKnTPpFv7u9OdJ09NtpDf/yb/Z8mkyya7Y/+qjAMN1PhA",
	"zXwI6qOi4n+2f9br/ljNizgHD5PnhPyxKAqA8q6LhUriWgzCpgH3oNagjL/F8uewdw9Z2Y7JXqKL9U8m",
	"3TrYaOX63sHcX+0XqUk3On/u5HcW28uZ0V9bI/9i7f+jTYCXJlvo7D006XJBZWIDzjYbyRIuiwDEK7Zk",
	"3kxAqiuRP9HDY5gEisVUqAo2fuH4JRpEJXq+LKtWjdZGLxm9aSHfLi79dBq1H/22//oBBv9x3I4xTq1b",
	"Bj4Ab7Qmcc5tJ4co4JSrbuD3gNcPTLZr9D3LcZG4c0a3Opvf5s31fHP+qNXMt2faP6ybdOuDK3lz5vB7",
	"RFGkwLkSHulnAsWHWTHVJ+6L/0ncb7J0z7NXYuL+uzq2tUPeK2zWy8+8fYgKg+8Y/dTqccNolGdfGpzc",
	"uMkWyoSxZKbT3tDIFg6WXx3e/b2bFccKGCn0Noo2+jcAAP//JAWWY0cJAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
