// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// FileMetadata defines model for FileMetadata.
type FileMetadata struct {
	Id   *openapi_types.UUID `json:"id,omitempty"`
	Name *string             `json:"name,omitempty"`
	Size *int                `json:"size,omitempty"`
	Tags *[]string           `json:"tags,omitempty"`
}

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	FileId *openapi_types.UUID `json:"file_id,omitempty"`
	GcsUrl *string             `json:"gcs_url,omitempty"`
	Status *string             `json:"status,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Tags 検索用タグ（複数指定可能）
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`
}

// UploadFileMultipartBody defines parameters for UploadFile.
type UploadFileMultipartBody struct {
	// File アップロードするファイル本体
	File *openapi_types.File `json:"file,omitempty"`

	// Tags 検索用タグ
	Tags *[]string `json:"tags,omitempty"`

	// TenantId ビジネスオーナー識別子（将来のDB分離用）
	TenantId *string `json:"tenant_id,omitempty"`
}

// UploadFileMultipartRequestBody defines body for UploadFile for multipart/form-data ContentType.
type UploadFileMultipartRequestBody UploadFileMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// メタデータの一覧を取得する
	// (GET /files)
	ListFiles(ctx echo.Context, params ListFilesParams) error
	// システムの稼働状況と起動時パフォーマンスを返す
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// ファイルをアップロードし、メタデータを登録する
	// (POST /upload)
	UploadFile(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListFiles converts echo context to params.
func (w *ServerInterfaceWrapper) ListFiles(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFilesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tags", ctx.QueryParams(), &params.Tags, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tags: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListFiles(ctx, params)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// UploadFile converts echo context to params.
func (w *ServerInterfaceWrapper) UploadFile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadFile(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/files", wrapper.ListFiles)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.POST(baseURL+"/upload", wrapper.UploadFile)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6RV0W4bRRT9lWrgcYndlqd9o0KFSiBVCJ6qKprsXjtT7c5uZ2ZRTWQpu4MSN23VkDaE",
	"QCE0JG2gJI0okJS65GNu1nae8gtoZh0l8TrFiBfvemb2zrlnzjkzRbwojCMOXEniThHpTUJI7etlFsDH",
	"oKhPFTX/YxHFIBQDO8t881uLREgVcUmSMJ84RDViIC6RSjBeJ02HcBqCWViakOyLkxOMK6iDMDOK1osd",
	"FIRy6Lf9ASoEbZDm8UA0cQM8ZVZ8FgcR9T8BGUdcQhl9jQUwPmILdU+OJyIY3oWiKrEV4RYN48DOJp4H",
	"UpZLlYGaIcZrkSngg/QEixWLOHEJZs9R/4K6jfoFZqvmJdtEPWPHU9Q/YfosX/kL03VMv8R0ZX/3Sd5a",
	"Qr2I2WPM1lA/671aPZhO37t6xQBhykK7SgUNAgjOmbM996mgXNZAnCsWfQ5CFpufH6uOVU17UQycxoy4",
	"5OJYdewicUhM1aTtt2IotG91UOZh6KUG/RWfuOQjJtVlu8J8I2gICoQk7rUpwswWNxMQDXKkDxKwkCni",
	"9OVX0FGjSaCIe6HqlETSdIaXiWo1CWfUOaPMado7a4+6v692H25gtofZ9mG71Vub7Sxud+7O5lvf5vef",
	"9/Trw/Zt4hC4FQeRD8RVIgFnKBor5JNYRlb0dYeIvnbt+gvVqnl4EVfALds0jgPmWb4rN6TBPjVso7cF",
	"1IhL3qocu7zSt3jllL/LGJrOIDet+XxuxcpYJmFIRcPoVD82VOlZq9A9TLf2d6d7T55itpDf/zr/ewnT",
	"Zczu2K8qk0ADNXmmZj4A9WGx4n+2f9rr/sS4F3EOngL/BPkTURQA5X0XC5XE4zEImwbcg/E6ZfxfLD+C",
	"vQfIynYwe2lcrH/EdKu70c71ve7cn50XKaYbvT928juLneUM9VfWyD9b+/9gE+AlZgu9vYeYLhdUJjbg",
	"bLORHMJlEYDmiC2ZNxOQ6lLkNwZ4DJNAsZgKVTGNv3MU9WdRaTw/LKtWUWvUS6g3LeTbxaGfTKPOo1/3",
	"Xz8gznHcTjBOrVvKZuhfAG+0JnFGtpNDFHDKVT/wB8DrB5jtor5nOS4Sdw51u7f5Td5azzfnD9utfHum",
	"8/06plvvX8pbMwffGRRFCoyU8IZ+Joz4TFY0S+I+/5/E/SZLD1x7Q0xcPqsjWzvk3cJmg/zM24uoMPgO",
	"6qdWjxuojTxLaXB84pgtDBPGEk6ng6GRLXSXXx3c/a2fFUcKuFbo7bqx0T8BAAD//0GRRoGoCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
