# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x04\x66ile\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n\x11UploadFileRequest\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x12.file.FileMetadataH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"t\n\x0c\x46ileMetadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x15\n\rexpected_size\x18\x06 \x01(\x03\"\x96\x01\n\x0f\x46ileIngestEvent\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"5\n\x12\x46ileIngestResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x12UploadFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"?\n\x10ListFilesRequest\x12\x0c\n\x04tags\x18\x01 \x03(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"6\n\x11ListFilesResponse\x12!\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x12.file.FileMetadata2\xcf\x01\n\x0b\x46ileService\x12\x41\n\nUploadFile\x12\x17.file.UploadFileRequest\x1a\x18.file.UploadFileResponse(\x01\x12<\n\tListFiles\x12\x16.file.ListFilesRequest\x1a\x17.file.ListFilesResponse\x12?\n\x0cNotifyIngest\x12\x15.file.FileIngestEvent\x1a\x18.file.FileIngestResponseB3Z1file-transfer-api/internal/handler/grpc/pb;filepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1file-transfer-api/internal/handler/grpc/pb;filepb'
  _globals['_UPLOADFILEREQUEST']._serialized_start=53
  _globals['_UPLOADFILEREQUEST']._serialized_end=137
  _globals['_FILEMETADATA']._serialized_start=139
  _globals['_FILEMETADATA']._serialized_end=255
  _globals['_FILEINGESTEVENT']._serialized_start=258
  _globals['_FILEINGESTEVENT']._serialized_end=408
  _globals['_FILEINGESTRESPONSE']._serialized_start=410
  _globals['_FILEINGESTRESPONSE']._serialized_end=463
  _globals['_UPLOADFILERESPONSE']._serialized_start=465
  _globals['_UPLOADFILERESPONSE']._serialized_end=518
  _globals['_LISTFILESREQUEST']._serialized_start=520
  _globals['_LISTFILESREQUEST']._serialized_end=583
  _globals['_LISTFILESRESPONSE']._serialized_start=585
  _globals['_LISTFILESRESPONSE']._serialized_end=639
  _globals['_FILESERVICE']._serialized_start=642
  _globals['_FILESERVICE']._serialized_end=849
# @@protoc_insertion_point(module_scope)
